### PR TITLE
Update d4d_menu.c

### PR DESCRIPTION
**Pull request by x0x1x2**
align the scroll bar position with in the d4d_menu object

### CODE REVIEW

**Comment by Gargy007** [comment]
Hi,
 at the moemnt I can't check it in debugger, but could you explain more the change of the object pointer?

Because I think that this should be OK that the orifginal object is used for get the new position of the scrool bar object.

Thanks for explanation.
Petr

**Comment by x0x1x2** [comment]
Hi
Please review:
https://community.freescale.com/message/520192?tstart=0#520192

**Comment by Gargy007** [comment]
Hi,
 you right there should be BUG.

I don't have a hardware at the moment on my desk, but could you try one
thing?

Just comment the line that you change - this should be right solution as I
think.

Thank you
Petr

2015-06-01 17:38 GMT+02:00 Joni <notifications@github.com>:

**Comment by x0x1x2** [comment]
Hi
I comment the specific line, but it's not solve the problem.

**Comment by Gargy007** [comment]
OK thanks,
 I go to find HW, I will keep you informed.

Thank  you
Petr

2015-06-02 8:35 GMT+02:00 Joni <notifications@github.com>:

**Comment by Gargy007** [comment]
Hi,
 I finally understood the core of the issue, and you right. Your solution is fine.

Thank you.

**Pull request merged**
